language:
    - cpp

compiler:
    - clang
    - gcc

sudo: required
dist: trusty

env:
    # static build does not work with gcc on travis for some reason
    - BUILD_EXAMPLES="ON" BUILD_TESTS="ON" CMAKE_BUILD_TYPE="Release"
      #- BUILD_EXAMPLES="ON" BUILD_TESTS="ON" BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Release"
    - BUILD_EXAMPLES="ON" BUILD_TESTS="ON" CMAKE_BUILD_TYPE="Debug"
      #- BUILD_EXAMPLES="ON" BUILD_TESTS="ON" BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Debug"

before_install:
    - git submodule update --init --recursive

install:
    - sudo apt-get update
    - sudo apt-get install -y clang-3.6 g++-4.8 libboost-all-dev libssl-dev libtbb-dev cmake

before_script:
    # update compilers
    - if [ "${CXX}" == "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - if [ "${CXX}" == "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi

script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} -DBUILD_TESTS=${BUILD_TESTS} -DBUILD_EXAMPLES=${BUILD_EXAMPLES} ..
    - make VERBOSE=1
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make test || cat Testing/Temporary/LastTest.log ; fi
    - make package

env:
  global:
   - secure: "aniUHYHxhL+P0wddpW5zkZE5NEPD+BKwb7FN2TojQ4q2dZ6U3bJwsm/iyhrj+/d6gtde8pWUuRLEQ9aGf2Zoxn7uahjgPCnFGskGtOV+vpDlvWl4wXioEYdom+ztHd2MDCeA2mFjRCo923IWEbLmMnx6lSlyNLcmVi+CHU/Hm0o="

addons:
  coverity_scan:
    project:
      name: "daedric/httpp"
      description: "Micro HTTP server/client"
    notification_email: thomas.sanchz@gmail.com
    build_command_prepend: "make cmake"
    build_command:   "make -C build"
    branch_pattern:  coverity
